@startuml
'https://plantuml.com/class-diagram

interface MessageService{
+void sendMessage(String,String,String)
+void getMessages(String,String)
}

class FriendsMessageServiceImpl {
-{static} MessageService friendMessageService
==
+{static} MessageService getInstance()
+void sendMessage(String,String,String)
+void getMessages(String,String)
}

FriendsMessageServiceImpl ..|> MessageService
@enduml