@startuml
'https://plantuml.com/class-diagram

interface FriendsService{
+void addAgree(String,String)
+void getFriendList(String)
+void addFriend(String,String)
+void deleteFriend(String,String)
}

class FriendsServiceImpl {
-{static} FriendsService friendService
==
+{static} FriendsService getInstance()
+void addAgree(String,String)
+void getFriendList(String)
+void addFriend(String,String)
+void deleteFriend(String,String)
}

FriendsServiceImpl ..|> FriendsService
@enduml