[@startuml
'https://plantuml.com/activity-diagram-beta

start
:获取用户的未读消息;
if (用户是否有未读消息) then (否)
: 获取用户的未读消息失败;
    else (是)
    : 获取用户的未读消息成功;
    : 设置用户所有消息为已读状态;
endif
stop

start
:发送消息;
if(消息是否已读) then (是)
    :增加一条新消息;
    else(否)
    :无消息发送;
endif
stop

start
:用户请求添加好友;
if(被添加用户是否在线)then(否)
    :设置消息未读;
    :为被添加用户设置一条新消息,在上线后提醒;
    else(是)
    :设置消息已读;
    :为被添加用户设置一条新消息;
endif
stop

start
:获得消息记录;
if(是否成功获得消息记录) then (是)
    :获得消息记录成功;
    else(否)
    :获得消息记录失败;
endif
stop
@enduml
]