[@startuml
'https://plantuml.com/activity-diagram-beta

start
:发送群组消息;
:获取群组中用户列表;
:在消息列表中添加群组消息;
if(是否成功添加群组消息) then (否)
	:发送群组消息失败;
	else(是)
	if (群组中用户是否在线) then (是)
	: 发送群组消息成功 ;
	    else (否)
	    : 发送群组消息失败,消息会在用户上线后发送;
	endif
endif

stop

start
:获取群聊消息;
if(是否成功获取群聊消息)then(是)
    :获取群聊消息成功;
    else(否)
    :获取群聊消息失败;
endif
stop

start
:删除过期群聊消息;
:获取时间;
if(是否成功删除过期群聊消息)then(是)
    :删除此时间之前的群聊消息;
    else(否)
    :删除过期群聊消息失败;
endif
stop


@enduml
]