@startuml
'https://plantuml.com/class-diagram


annotation Mapper

interface GroupMapper {
+int deleteByGroupName(String)
+int update(Group)
+int add(Group)
+Group getByLeaderId(Integer)
+Group getByGroupName(String)
}

annotation Repository{
+String value()
}

GroupMapper .. Mapper
GroupMapper .. Repository

@enduml