@startuml
'https://plantuml.com/class-diagram


annotation Mapper

interface MessageMapper {
+int add(Message)
+int addList(List<Message>)
+List<Message> getFriendMessage(String,String)
+List<Message> getGroupMessage(String)
+int setMessageReaded(String)
+List<Message> getNotReadMessage(String)
+List<Message> getAllMessages()
+int delete(Date)
}

annotation Repository{
+String value()
}

MessageMapper .. Mapper
MessageMapper .. Repository

@enduml