@startuml
'https://plantuml.com/class-diagram

annotation Data
interface Serializable

+class Message {
-{static}long serialVersionUID
-Boolean isRead
-Boolean isGroupMessage
-String messageType
-String receiverName
-String senderName
-String content
-Date sendTime
-Integer id
}

Serializable <|.. Message
Data .. Message
@enduml