@startuml


新用户 -> 系统 : 注册信息
系统 --> 新用户 : 返回信息（成功或失败）

已存在的用户 -> 系统 : 请求登录

group 验证结果 [失败]

    已存在的用户 <-- 系统 : 登陆失败

else 成功

    loop
        已存在的用户 -> 系统 : 发送请求(具体见用例图)
        已存在的用户 <-- 系统 : 对用户的请求做出响应
    end
    已存在的用户 -> 系统 : 用户退出登录
end

@enduml