@startuml

新用户 -> 系统 : 注册信息(用户名, 密码)
alt 校验成功
    系统 --> 新用户 : 注册成功
else 校验失败
    系统 --> 新用户 : 注册失败
end

alt 密码登录
    用户1 -> 系统 : 登录请求(用户名, 密码)
else 人脸登录
    用户1 -> 系统 : 登录请求(用户名, 人脸信息)
end

alt 检验失败
    用户1 <-- 系统 : 登录失败
else 成功
    用户1 <-- 系统 : 登录成功, 返回未读消息

    activate 用户1

    loop 添加人脸

        用户1 -> 系统 : 添加人脸(用户名, 人脸信息)
        alt 成功
            用户1 <-- 系统 : 操作成功
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 修改密码

        用户1 -> 系统: 修改密码(用户名, 密码)
        alt 成功
            用户1 <-- 系统 : 操作成功
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 用户获取好友列表

        用户1 -> 系统 : 获取好友列表(用户名)
        alt 成功
            用户1 <-- 系统 : 发送好友列表
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 删除好友

        用户1 -> 系统 : 删除好友(用户名, 好友名)
        alt 成功
            用户1 <-- 系统 : 操作成功
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 添加好友

        用户1 -> 系统 : 添加用户2为好友(用户名, 好友名)
        alt 用户2在线
            系统 -> 用户2 : 用户1请求添加你为好友(用户名, 好友名)
            alt 添加成功
                用户2 --> 系统 : 同意(用户名, 好友名)
                系统 --> 用户1 : 添加成功
            else 添加失败
                用户2 --> 系统 : 拒绝
            end
        else 用户2不在线
            系统 --> 用户1 : 对方不在线, 消息将在对方上线后收到
        end

    else 同意好友申请

        用户1 -> 系统: 同意好友申请(用户名, 好友名)

    else 获取群聊列表

        用户1 -> 系统 : 获取群聊列表(用户名)
        alt 成功
            用户1 <-- 系统 : 用户群聊列表
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 建立群聊

        用户1 -> 系统 : 建立群聊(用户名, 群聊信息)
        alt 操作失败
            用户1 <-- 系统 : 操作失败
        end

    else 加入群聊

        用户1 -> 系统 : 加入群聊(用户名, 群聊名)
        alt 操作失败
            用户1 <-- 系统 : 操作失败
        end

    else 离开群聊

        用户1 -> 系统 : 离开群聊(用户名, 群聊名)
        alt 操作失败
            用户1 <-- 系统 : 操作失败
        end

    else 获取群聊的详细信息

        用户1 -> 系统 : 获取群聊信息(用户名, 群聊名)
        alt 成功
            用户1 <-- 系统 : 群聊详细信息
        else 失败
            用户1 <-- 系统 : 操作失败
        end

    else 获取消息记录

        alt 获取群聊消息记录
            用户1 -> 系统 : 获取群聊消息记录(用户名, 群聊名)
            alt 成功
                用户1 <-- 系统 : 群聊记录
            else 失败
                用户1 <-- 系统 : 失败
            end
        else 获取好友消息记录
            用户1 -> 系统 : 获取好友消息记录(用户名, 好友名)
            alt 成功
                用户1 <-- 系统 : 好友聊天记录
            else 失败
                用户1 <-- 系统 : 操作失败
            end
        end

    else 发送消息

        alt 发送群聊消息
            用户1 -> 系统 : 发送群聊消息(用户名, 群聊名, 消息内容)
            alt 失败
                系统 --> 用户1 : 消息发送失败, 请重新发送
            end
        else 发送好友消息
            用户1 -> 系统 : 发送好友消息(用户名, 好友名, 消息内容)
            alt 用户3在线
                用户3 <- 系统 : 用户1发送一条消息
            else 用户3不在线
                系统-->用户1 : 用户3不在线,消息会在用户3上线时送达
            end
        end
    end

end

用户1 -> 系统 : 退出登录(用户名)
deactivate 用户1


@enduml