@startuml
'https://plantuml.com/class-diagram

interface FriendService{
+boolean addAgree(String,String)
+boolean removeFriend(String,String)
+List<String> getFriendList(String)
}

class FriendServiceImpl {
-FriendsMapper friendsMapper
==
+boolean addAgree(String,String)
+boolean removeFriend(String,String)
+List<String> getFriendList(String)
}

annotation Service{
+String value()
}

FriendServiceImpl .. Service
FriendServiceImpl ..|> FriendService
@enduml