@startuml
'https://plantuml.com/class-diagram

interface UserMapper {

	+int update(User)
	+int deleteFace(String)
	+List<User> getAll()
	+int changePassword(String,String)
	+int delete(String)
	+int addFace(String,String)
	+int add(User)
	+User getByUsername(String)

}

annotation Repository{
+String value()
}

annotation Mapper

UserMapper .. Mapper
UserMapper .. Repository

@enduml